version: "3.8"
services:
  web:
    container_name: RiskFrontDev
    build: .
    restart: always
    # environment:
    #   - NODE_ENV=staging
    # command: npm  start
    ports:
      - "3015:3015"
